# Generated by Django 5.0.6 on 2024-07-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tiltle_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datacompleated',
            new_name='datcompleted',
        ),
    ]
