# Generated by Django 5.0.6 on 2024-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_datacompleated_task_datcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datcompleted',
        ),
        migrations.AddField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
